### ISSUE TITLE
Storing personal data inside `yaml` file

### ISSUE THREAD

**Issue by S1SYPHOS** [MrRo-de/Bitpanda-Report#1]
Hey there,
it seems easier for most people to store information like `full_name`, `street` etc inside a `.yml` file - if that sounds about right, I'd be happy to provide a PR, just let me know!

Cheers,
S1SYPHOS

**// Edit:**
Come to think about it, your script could benefit from this for several options, too :fox_face:

**Comment by MrRo-de** [comment]
Hi,

Thanks for your suggestion.
I haven't worked with .yml before, but i will have a look into it.

What would be the other options the script could benefit from a .yml file?

best regards

**Comment by S1SYPHOS** [comment]
Well, for one you could define the path where the output should be stored (you seem to have hardcoded the user's desktop), so this would add some more flexibility. Further down the road, it could be used to set the desired `date_format`, the title of the report (currently 'Bitpanda Report') to make it more personal (since most people cannot edit the generated PDF afterwards) or exclude asset classes from the report (seems that submitting the example `csv` and removing the only `metal` purchase leads to an `IndexError`, gotta investigate).

Maybe I'll fork it and add `click` library for more CLI features out-of-the-box, ofc providing proper credit & leaving the opportunity to donate crypto in your favor intact (last page)
